### ISSUE TITLE
Problem with Meteor 1.3!

### ISSUE THREAD

**Issue by thearabbit** [ortexx/load-alias#1]
I tried use this package with `Meteor 1.3`, but don't work

``` js
var LoadAlias = require('load-alias');

var loadConfig = {
    startup: '../imports/modules/core/startup/client',
}

var load = new LoadAlias(loadConfig) // or new loadAlias(rootPath, loadConfig)

global.load = load;

console.log(load.getPath('@startup'));

load('@startup/index.js');
```

It show

``` js
../imports/modules/core/startup/client
install.js:78Uncaught Error: Cannot find module '../imports/modules/core/startup/client/index.js'
```

**Comment by ortexx** [comment]
.load() result is merge load.rootPath and your config alias path:
`load.rootPath + '../imports/modules/core/startup/client'`

Your error shows:
1) In meteor environment maybe the default load.rootPath is empty, set this yourself if it's true. 
2) Config alias path can't include ../, set load.rootPath instead of ../ 

```
load.rootPath = 'full path before imports/modules/core/startup/client ' // this is the starting point for all config aliases of this LoadAlias instance
// example: /home/user/www/project/

var loadConfig = {
    startup: 'imports/modules/core/startup/client',
}

console.log(load.getFullPath('@startup')) // /home/user/www/project/imports/modules/core/startup/client

var correctResult = load('@startup');
```

Use console.log(load.getFullPath()) for showing full require path.

If you need different starting points for different imported files, use several instances of LoadAlias

```
var load = new LoadAlias('rootPath1', loadConfig1);
var load2 = new LoadAlias('rootPath2', loadConfig2);
...
```

And update please to new version. There are process.cwd() checking too for default .rootPath.

**Comment by thearabbit** [comment]
Thanks for reply, but I don't understand how to config the `rootPath`.
My structure (Mac):
Startup File

``` js
// Users/theara/Documents/meteor_app/test-blaze1.3/imports/modules/core/startup/client/index.js
import './routes.js';
```

Load File

``` js
// Users/theara/Documents/meteor_app/test-blaze1.3/client/main.js
var LoadAlias = require('load-alias');

var loadConfig = {
    startup: 'imports/modules/core/startup/client',
}

var load = new LoadAlias(loadConfig)

console.log(load.getFullPath('@startup'));

load('@startup/index.js');
```

Please help me.

**Comment by thearabbit** [comment]
I tried

``` js
var LoadAlias = require('load-alias');

var loadConfig = {
    startup: 'core/startup/client',
};

var load = new LoadAlias(loadConfig);

load.rootPath = '../imports/modules/';

console.log(load.getFullPath('@startup')); // show: '../imports/modules/core/startup/client'

// don't work to load
load(load.getFullPath('@startup'));

// work, but I would like to use dynamic path
require('../imports/modules/core/startup/client');
```

**Comment by ortexx** [comment]
1) not load(load.getFullPath('@startup'));

`load('@startup');`

load.getFullPath only return string of full path
load(path) is require file using load.rootPath + path

2) .rootPath must absolute path, not relative like as ../
it is necessary to load files from anywhere.

your code must be, for example:

```
var LoadAlias = require('load-alias');

var loadConfig = {
    startup: 'imports/modules/core/startup/client',
};

var load = new LoadAlias(loadConfig);

load.rootPath = "Users/theara/Documents/meteor_app/test-blaze1.3/";

load('@startup');
```

but you can set this load.rootPath "Users/theara/Documents/meteor_app/test-blaze1.3/" dynamically using nodejs environment (process.cwd(), process.env.INIT_CWD e.t.c)

In the current version of package (0.0.7), default .rootPath is set using the most popular variants of starting point (listed above)

Check you version. If it is the last version and .rootPath is empty, set it yourself  given your environment

**Comment by thearabbit** [comment]
Still don't work

``` js
// client/main.js

var LoadAlias = require('load-alias');

var loadConfig = {
    startup: 'import/modules/core/startup/client',
};

var load = new LoadAlias(loadConfig);


load.rootPath = process.env.INIT_CWD || process.cwd();

console.log(load.getPath('@startup'));
console.log(load.getFullPath('@startup'));

load('@startup');
```

![2016-04-24_16-05-09](https://cloud.githubusercontent.com/assets/4495160/14766525/190a8686-0a38-11e6-8ec9-24779af80d9a.png)

**Comment by ortexx** [comment]
you forgot "s" in "import":

```
var loadConfig = {
    startup: 'import/modules/core/startup/client/index.js', // need imports/modules/core/startup/client/index.js
};
```

**Comment by thearabbit** [comment]
Thanks for your helping, but don't work

``` js
var LoadAlias = require('load-alias');

var loadConfig = {
    startup: 'imports/modules/core/startup/client/index.js',
};

var load = new LoadAlias(loadConfig);


//load.rootPath = process.env.INIT_CWD || process.cwd();

console.log(load.getPath('@startup'));
console.log(load.getFullPath('@startup'));

load('@startup');
```

![2016-04-24_17-42-14](https://cloud.githubusercontent.com/assets/4495160/14766935/2a7c195a-0a44-11e6-910a-516f0d2207dc.png)

**Comment by thearabbit** [comment]
Excuse me, would I like to use dynamic path with `require()` or not?

``` js
let path = '../imports/modules/core/startup/client/index.js';

require(path);
```

**Comment by ortexx** [comment]
I've never used meteor, "load-alias" works on the server-side using "require" nodejs native method inside;
Maybe I'll find time in the near future for testing meteor.

> Excuse me, would I like to use dynamic path with require() or not?

I don't understand your question. Maybe you about this: `load(path, false)`
